"use client";

/**
 * Input side of the Post brief. The six columns were already writable through
 * /api/publish (validated by post-brief-input.ts) but had no UI, so a brief
 * generated by the model could be read and never corrected. These fields close
 * that gap.
 *
 * Caps come from BRIEF_LIMITS so the client shows the same limits the server
 * enforces — the server still validates, this only avoids a pointless 400.
 */

import { Plus, TrashSimple, X } from "@phosphor-icons/react";
import { BRIEF_LIMITS, type PostBrief } from "@/lib/creative-brief";
import { PLATFORM_LABELS, label } from "@/lib/creative-labels";

/** The channels /api/publish accepts, mirroring PUBLISH_CHANNEL_VALUES. */
const CHANNEL_OPTIONS = ["facebook", "instagram", "tiktok", "zalo"] as const;

export const EMPTY_BRIEF: PostBrief = {
  title: null,
  summary: null,
  outline: [],
  hooks: [],
  topicTags: [],
  targetChannels: [],
};

/** Editable draft shape: text fields are plain strings while being typed. */
export interface BriefDraft {
  title: string;
  summary: string;
  outline: string[];
  hooks: string[];
  topicTags: string[];
  targetChannels: string[];
}

export function briefToDraft(brief: PostBrief | undefined): BriefDraft {
  const source = brief ?? EMPTY_BRIEF;
  return {
    title: source.title ?? "",
    summary: source.summary ?? "",
    outline: [...source.outline],
    hooks: [...source.hooks],
    topicTags: [...source.topicTags],
    targetChannels: [...source.targetChannels],
  };
}

/** Request body for the brief half of a save. Blank text clears the column. */
export function draftToPayload(draft: BriefDraft) {
  return {
    title: draft.title.trim() || null,
    summary: draft.summary.trim() || null,
    outline: draft.outline.map((item) => item.trim()).filter(Boolean),
    hooks: draft.hooks.map((item) => item.trim()).filter(Boolean),
    topicTags: draft.topicTags.map((item) => item.trim()).filter(Boolean),
    targetChannels: draft.targetChannels,
  };
}

function FieldLabel({ text, hint }: { text: string; hint?: string }) {
  return (
    <div className="flex items-baseline justify-between gap-2">
      <span className="text-[12px] font-bold text-[var(--text-secondary)]">{text}</span>
      {hint && <span className="text-[11px] tabular-nums text-[var(--text-muted)]">{hint}</span>}
    </div>
  );
}

const inputClass =
  "w-full rounded-[9px] border border-[var(--border-strong)] bg-[var(--bg)] px-3 py-2 text-[13px] text-[var(--text)] outline-none transition-colors placeholder:text-[var(--text-muted)] focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--brand-ring)]";

/** An ordered list of short lines: add, edit, remove. Used for outline and hooks. */
function ListEditor({
  items,
  onChange,
  maxItems,
  itemLabel,
  addLabel,
  placeholder,
  ordered,
}: {
  items: string[];
  onChange: (next: string[]) => void;
  maxItems: number;
  /** Names each row for screen readers, e.g. "Ý 3" / "Hook 2". */
  itemLabel: string;
  addLabel: string;
  placeholder: string;
  ordered: boolean;
}) {
  const full = items.length >= maxItems;
  return (
    <div className="space-y-1.5">
      {items.map((item, index) => (
        <div key={index} className="flex items-start gap-2">
          <span className="mt-2 flex h-5 w-5 shrink-0 items-center justify-center rounded-[6px] bg-[var(--bg-subtle)] text-[10.5px] font-bold tabular-nums text-[var(--text-muted)]">
            {ordered ? index + 1 : "•"}
          </span>
          <input
            value={item}
            aria-label={`${itemLabel} ${index + 1}`}
            maxLength={BRIEF_LIMITS.itemLength}
            placeholder={placeholder}
            onChange={(event) => {
              const next = [...items];
              next[index] = event.target.value;
              onChange(next);
            }}
            className={inputClass}
          />
          <button
            type="button"
            onClick={() => onChange(items.filter((_, at) => at !== index))}
            aria-label={`Xóa ${itemLabel.toLowerCase()} ${index + 1}`}
            className="mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-[8px] text-[var(--text-muted)] transition-colors hover:bg-[var(--danger-light)] hover:text-[var(--danger)]"
          >
            <TrashSimple size={15} aria-hidden="true" />
          </button>
        </div>
      ))}
      <button
        type="button"
        onClick={() => onChange([...items, ""])}
        disabled={full}
        className="flex items-center gap-1.5 rounded-[8px] px-1.5 py-1 text-[12px] font-bold text-[var(--accent)] transition-opacity hover:opacity-70 disabled:cursor-not-allowed disabled:text-[var(--text-muted)] disabled:opacity-60"
      >
        <Plus size={13} weight="bold" aria-hidden="true" />
        {full ? `Đã đủ ${maxItems} mục` : addLabel}
      </button>
    </div>
  );
}

/** Free-text tags entered one at a time. */
function TagEditor({ items, onChange, maxItems }: { items: string[]; onChange: (next: string[]) => void; maxItems: number }) {
  const full = items.length >= maxItems;
  return (
    <div>
      {items.length > 0 && (
        <ul className="mb-2 flex flex-wrap gap-1.5">
          {items.map((item, index) => (
            <li
              key={`${index}-${item}`}
              className="flex items-center gap-1 rounded-[6px] bg-[var(--accent-light)] py-0.5 pl-2 pr-1 text-[11.5px] font-bold text-[var(--accent)]"
            >
              {item}
              <button
                type="button"
                onClick={() => onChange(items.filter((_, at) => at !== index))}
                aria-label={`Bỏ thẻ ${item}`}
                className="flex h-4 w-4 items-center justify-center rounded-[4px] transition-colors hover:bg-[var(--accent)]/20"
              >
                <X size={10} weight="bold" aria-hidden="true" />
              </button>
            </li>
          ))}
        </ul>
      )}
      <input
        aria-label="Thêm thẻ chủ đề"
        placeholder={full ? `Đã đủ ${maxItems} thẻ` : "Nhập thẻ rồi Enter"}
        disabled={full}
        maxLength={BRIEF_LIMITS.tagLength}
        onKeyDown={(event) => {
          if (event.key !== "Enter") return;
          event.preventDefault();
          const value = event.currentTarget.value.trim();
          if (!value || items.includes(value)) return;
          onChange([...items, value]);
          event.currentTarget.value = "";
        }}
        className={`${inputClass} disabled:cursor-not-allowed disabled:opacity-60`}
      />
    </div>
  );
}

/**
 * Channel picker. `connected` marks channels with stored credentials; an
 * unconnected channel can still be chosen (it is the author's intent, and the
 * publish flow decides what is possible) but is labelled so the choice is informed.
 */
function ChannelPicker({
  selected,
  connected,
  onChange,
}: {
  selected: string[];
  connected?: string[];
  onChange: (next: string[]) => void;
}) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {CHANNEL_OPTIONS.map((channel) => {
        const active = selected.includes(channel);
        const known = !connected || connected.includes(channel);
        return (
          <button
            key={channel}
            type="button"
            aria-pressed={active}
            title={known ? undefined : "Kênh này chưa được kết nối"}
            onClick={() => onChange(active ? selected.filter((item) => item !== channel) : [...selected, channel])}
            className={`rounded-[8px] border px-2.5 py-1.5 text-[12px] font-bold transition-colors ${
              active
                ? "border-[var(--accent)] bg-[var(--accent)] text-[var(--accent-foreground)]"
                : "border-[var(--border-strong)] bg-[var(--bg)] text-[var(--text-secondary)] hover:border-[var(--accent)] hover:text-[var(--accent)]"
            }`}
          >
            {label(PLATFORM_LABELS, channel)}
            {!known && <span className={`ml-1 font-semibold ${active ? "opacity-80" : "text-[var(--text-muted)]"}`}>· chưa kết nối</span>}
          </button>
        );
      })}
    </div>
  );
}

export function BriefFields({
  draft,
  onChange,
  connectedChannels,
}: {
  draft: BriefDraft;
  onChange: (next: BriefDraft) => void;
  connectedChannels?: string[];
}) {
  const patch = (part: Partial<BriefDraft>) => onChange({ ...draft, ...part });

  return (
    <div className="space-y-4">
      <div className="space-y-1.5">
        <FieldLabel text="Tiêu đề" hint={`${draft.title.length}/${BRIEF_LIMITS.title}`} />
        <input
          value={draft.title}
          aria-label="Tiêu đề bài viết"
          maxLength={BRIEF_LIMITS.title}
          placeholder="Tiêu đề ngắn cho bài viết"
          onChange={(event) => patch({ title: event.target.value })}
          className={inputClass}
        />
      </div>

      <div className="space-y-1.5">
        <FieldLabel text="Tóm tắt" hint={`${draft.summary.length}/${BRIEF_LIMITS.summary}`} />
        <textarea
          value={draft.summary}
          aria-label="Tóm tắt bài viết"
          rows={3}
          maxLength={BRIEF_LIMITS.summary}
          placeholder="Bài này nói về điều gì, dành cho ai"
          onChange={(event) => patch({ summary: event.target.value })}
          className={`${inputClass} resize-y leading-relaxed`}
        />
      </div>

      <div className="space-y-1.5">
        <FieldLabel text="Dàn ý nội dung" hint={`${draft.outline.length}/${BRIEF_LIMITS.outlineItems}`} />
        <ListEditor
          items={draft.outline}
          onChange={(outline) => patch({ outline })}
          maxItems={BRIEF_LIMITS.outlineItems}
          itemLabel="Ý"
          addLabel="Thêm ý"
          placeholder="Một ý trong dàn bài"
          ordered
        />
      </div>

      <div className="space-y-1.5">
        <FieldLabel text="Hook mở bài" hint={`${draft.hooks.length}/${BRIEF_LIMITS.hookItems}`} />
        <ListEditor
          items={draft.hooks}
          onChange={(hooks) => patch({ hooks })}
          maxItems={BRIEF_LIMITS.hookItems}
          itemLabel="Hook"
          addLabel="Thêm hook"
          placeholder="Câu mở đầu thu hút"
          ordered
        />
      </div>

      <div className="space-y-1.5">
        <FieldLabel text="Thẻ chủ đề" hint={`${draft.topicTags.length}/${BRIEF_LIMITS.topicTagItems}`} />
        <TagEditor items={draft.topicTags} onChange={(topicTags) => patch({ topicTags })} maxItems={BRIEF_LIMITS.topicTagItems} />
      </div>

      <div className="space-y-1.5">
        <FieldLabel text="Kênh dự định đăng" />
        <ChannelPicker
          selected={draft.targetChannels}
          connected={connectedChannels}
          onChange={(targetChannels) => patch({ targetChannels })}
        />
      </div>
    </div>
  );
}
