import {
  Archive,
  ArrowsSplit,
  BookOpen,
  Brain,
  Buildings,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  ChartBar,
  ChartLineUp,
  ChatCircleDots,
  ChatsTeardrop,
  Eye,
  FilmSlate,
  FirstAidKit,
  Flame,
  GearSix,
  Globe,
  House,
  ImageSquare,
  Lightning,
  Megaphone,
  NotePencil,
  Palette,
  Plugs,
  Robot,
  Scan,
  ShieldCheck,
  Sparkle,
  Stack,
  Tag,
  TrendUp,
  UserCircle,
  UsersThree,
} from "@phosphor-icons/react";
import type { Icon } from "@phosphor-icons/react";
import type { RouteIconKey } from "./routes";

export const ROUTE_ICONS: Record<RouteIconKey, Icon> = {
  "ab-test": ArrowsSplit,
  analytics: ChartBar,
  appointments: CalendarCheck,
  automation: Lightning,
  brain: Brain,
  brand: Buildings,
  "brand-kit": Palette,
  bulk: Stack,
  care: FirstAidKit,
  competitors: TrendUp,
  content: NotePencil,
  "content-research": Sparkle,
  council: ChatsTeardrop,
  crm: UsersThree,
  "facebook-ads": Megaphone,
  "google-business": Globe,
  holidays: CalendarDots,
  images: ImageSquare,
  inbox: ChatCircleDots,
  learning: Brain,
  library: Archive,
  listening: Eye,
  orchestrator: Robot,
  promotions: Tag,
  publish: CalendarBlank,
  quality: ShieldCheck,
  reports: ChartLineUp,
  sale: Flame,
  services: Plugs,
  settings: GearSix,
  "skin-ai": Scan,
  "staff-visuals": UserCircle,
  stories: BookOpen,
  "style-training": Brain,
  today: House,
  "video-studio": FilmSlate,
  zalo: Lightning,
};
